import { Chapter } from "../Modules/resources.js";
import { generated_smart_files } from "./Smart-Files.js";

// Variables
let written_chapters = {
    'TOTW #1': new Chapter('TOP OF THE WORLD', [
        generated_smart_files["TOTW #1 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #1 - Pg.1"],
        generated_smart_files["TOTW #1 - Pg.2"],
        generated_smart_files["TOTW #1 - Pg.3"],
        generated_smart_files["TOTW #1 - Pg.4"],
        generated_smart_files["TOTW #1 - Pg.5"],
    ]),
    'TOTW #1 Remastered': new Chapter('TOP OF THE WORLD #1 REMASTERED', [
        generated_smart_files["TOTW #1 Remaster - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #1 Remaster - Pg.1"],
        generated_smart_files["TOTW #1 Remaster - Pg.2"],
        generated_smart_files["TOTW #1 Remaster - Pg.3"],
        generated_smart_files["TOTW #1 Remaster - Pg.4"],
        generated_smart_files["TOTW #1 Remaster - Pg.5"],
    ]),
    'TOTW #2': new Chapter('TOP OF THE WORLD #2', [
        generated_smart_files["TOTW #2 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #2 - Pg.1"],
        generated_smart_files["TOTW #2 - Pg.2"],
        generated_smart_files["TOTW #2 - Pg.3"],
        generated_smart_files["TOTW #2 - Pg.4"],
        generated_smart_files["TOTW #2 - Pg.5"],
    ]),
    'TOTW #3': new Chapter('TOP OF THE WORLD #3 - THANKSGIVING', [
        generated_smart_files["TOTW #3 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #3 - Pg.1"],
        generated_smart_files["TOTW #3 - Pg.2"],
        generated_smart_files["TOTW #3 - Pg.3"],
        generated_smart_files["TOTW #3 - Pg.4"],
        generated_smart_files["TOTW #3 - Pg.5"],
    ]),
    'TOTW #4': new Chapter('TOP OF THE WORLD #4 - UHHH', [
        generated_smart_files["TOTW #4 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #4 - Pg.1"],
        generated_smart_files["TOTW #4 - Pg.2"],
        generated_smart_files["TOTW #4 - Pg.3"],
        generated_smart_files["TOTW #4 - Pg.4"],
        generated_smart_files["TOTW #4 - Pg.5"],
    ]),
    'TOTW #5': new Chapter('TOP OF THE WORLD #5 - YUH', [
        generated_smart_files["TOTW #5 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #5 - Pg.1"],
        generated_smart_files["TOTW #5 - Pg.2"],
        generated_smart_files["TOTW #5 - Pg.3"],
        generated_smart_files["TOTW #5 - Pg.4"],
        generated_smart_files["TOTW #5 - Pg.5"],
    ]),
    'TOTW #6': new Chapter('TOP OF THE WORLD #6 - I LOVE YOU', [
        generated_smart_files["TOTW #6 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #6 - Pg.1"],
        generated_smart_files["TOTW #6 - Pg.2"],
        generated_smart_files["TOTW #6 - Pg.3"],
        generated_smart_files["TOTW #6 - Pg.4"],
        generated_smart_files["TOTW #6 - Pg.5"],
    ]),
    'TOTW #7': new Chapter('TOP OF THE WORLD #7 - OH MAN', [
        generated_smart_files["TOTW #7 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #7 - Pg.1"],
        generated_smart_files["TOTW #7 - Pg.2"],
        generated_smart_files["TOTW #7 - Pg.3"],
        generated_smart_files["TOTW #7 - Pg.4"],
        generated_smart_files["TOTW #7 - Pg.5"],
    ]),
    'TOTW #8': new Chapter('TOP OF THE WORLD #8 - SURVIVE', [
        generated_smart_files["TOTW #8 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #8 - Pg.1"],
        generated_smart_files["TOTW #8 - Pg.2"],
        generated_smart_files["TOTW #8 - Pg.3"],
        generated_smart_files["TOTW #8 - Pg.4"],
        generated_smart_files["TOTW #8 - Pg.5"],
    ]),
    'TOTW #9': new Chapter('TOP OF THE WORLD #9 - WHAT AM I', [
        generated_smart_files["TOTW #9 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #9 - Pg.1"],
        generated_smart_files["TOTW #9 - Pg.2"],
        generated_smart_files["TOTW #9 - Pg.3"],
        generated_smart_files["TOTW #9 - Pg.4"],
        generated_smart_files["TOTW #9 - Pg.5"],
        generated_smart_files["TOTW #9 - Pg.6"],
        generated_smart_files["TOTW #9 - Pg.7"],
        generated_smart_files["TOTW #9 - Pg.8"],
        generated_smart_files["TOTW #9 - Pg.9"],
        generated_smart_files["TOTW #9 - Pg.10"],
    ]),
    'TOTW #10': new Chapter('TOP OF THE WORLD #10 - NEW CHARACTER', [
        generated_smart_files["TOTW #10 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #10 - Pg.1"],
        generated_smart_files["TOTW #10 - Pg.2"],
        generated_smart_files["TOTW #10 - Pg.3"],
        generated_smart_files["TOTW #10 - Pg.4"],
        generated_smart_files["TOTW #10 - Pg.5"],
    ]),
    'TOTW #11': new Chapter('TOP OF THE WORLD #11 - COOL', [
        generated_smart_files["TOTW #11 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #11 - Pg.1"],
        generated_smart_files["TOTW #11 - Pg.2"],
        generated_smart_files["TOTW #11 - Pg.3"],
        generated_smart_files["TOTW #11 - Pg.4"],
        generated_smart_files["TOTW #11 - Pg.5"],
    ]),
    'TOTW #12': new Chapter('TOP OF THE WORLD #12 - ROLLIN', [
        generated_smart_files["TOTW #12 - Cover"],
        generated_smart_files["TOTW #12 - Pg.1"],
        generated_smart_files["TOTW #12 - Pg.2"],
        generated_smart_files["TOTW #12 - Pg.3"],
        generated_smart_files["TOTW #12 - Pg.4"],
        generated_smart_files["TOTW #12 - Pg.5"],
        generated_smart_files["TOTW #12 - Pg.6"],
    ]),
    'TOTW #13': new Chapter('TOP OF THE WORLD #13 - JOB', [
        generated_smart_files["TOTW #13 - Cover"],
        generated_smart_files["TOTW #13 - Pg.1"],
        generated_smart_files["TOTW #13 - Pg.2"],
        generated_smart_files["TOTW #13 - Pg.3"],
        generated_smart_files["TOTW #13 - Pg.4"],
        generated_smart_files["TOTW #13 - Pg.5"],
        generated_smart_files["TOTW #13 - Pg.6"],
        generated_smart_files["TOTW #13 - Pg.7"],
        generated_smart_files["TOTW #13 - Pg.8"],
        generated_smart_files["TOTW #13 - Pg.9"],
        generated_smart_files["TOTW #13 - Pg.10"],
        generated_smart_files["TOTW #13 - Pg.11"],
        generated_smart_files["TOTW #13 - Pg.12"],
        generated_smart_files["TOTW #13 - Pg.13"],
        generated_smart_files["TOTW #13 - Pg.14"],
    ]),
    'TOTW #14': new Chapter('TOP OF THE WORLD #14 - NIKO', [
        generated_smart_files["TOTW #14 - Cover"],
        generated_smart_files["Blank"],
        generated_smart_files["TOTW #14 - Pg.1"],
        generated_smart_files["TOTW #14 - Pg.2"],
        generated_smart_files["TOTW #14 - Pg.3"],
        generated_smart_files["TOTW #14 - Pg.4"],
        generated_smart_files["TOTW #14 - Pg.5"],
    ]),
    'TOTW #15': new Chapter('TOP OF THE WORLD #15 - NAH', [
        generated_smart_files["TOTW #15 - Cover"],
        generated_smart_files["TOTW #15 - Pg.1"],
        generated_smart_files["TOTW #15 - Pg.2"],
        generated_smart_files["TOTW #15 - Pg.3"],
        generated_smart_files["TOTW #15 - Pg.4"],
        generated_smart_files["TOTW #15 - Pg.5"],
        generated_smart_files["TOTW #15 - Pg.6"],
    ]),
    'TOTW #16': new Chapter('TOP OF THE WORLD #16 - HEY PART 1', [
        generated_smart_files["TOTW #16 - Cover"],
        generated_smart_files["TOTW #16 - Pg.1"],
        generated_smart_files["TOTW #16 - Pg.2"],
        generated_smart_files["TOTW #16 - Pg.3"],
        generated_smart_files["TOTW #16 - Pg.4"],
        generated_smart_files["TOTW #16 - Pg.5"],
        generated_smart_files["TOTW #16 - Pg.6"],
        generated_smart_files["TOTW #16 - Pg.7"],
        generated_smart_files["TOTW #16 - Pg.8"],
        generated_smart_files["TOTW #16 - Pg.9"],
        generated_smart_files["TOTW #16 - Pg.10"],
        generated_smart_files["TOTW #16 - Pg.11"],
        generated_smart_files["TOTW #16 - Pg.12"],
        generated_smart_files["TOTW #16 - Pg.13"],
        generated_smart_files["TOTW #16 - Pg.14"],
        generated_smart_files["TOTW #16 - Pg.15"],
        generated_smart_files["TOTW #16 - Pg.16"],
        generated_smart_files["TOTW #16 - Pg.17"],
        generated_smart_files["TOTW #16 - Pg.18"],
        generated_smart_files["TOTW #16 - Pg.19"],
        generated_smart_files["TOTW #16 - Pg.20"],
    ]),
    'TOTW #17': new Chapter('TOP OF THE WORLD #17 - HEY PART 2', [
        generated_smart_files["TOTW #17 - Cover"],
        generated_smart_files["TOTW #17 - Pg.1"],
        generated_smart_files["TOTW #17 - Pg.2"],
        generated_smart_files["TOTW #17 - Pg.3"],
        generated_smart_files["TOTW #17 - Pg.4"],
        generated_smart_files["TOTW #17 - Pg.5"],
        generated_smart_files["TOTW #17 - Pg.6"],
    ]),
    'TOTW #18': new Chapter('TOP OF THE WORLD #18 - HEY PART 3', [
        generated_smart_files["TOTW #18 - Cover"],
        generated_smart_files["TOTW #18 - Pg.1"],
        generated_smart_files["TOTW #18 - Pg.2"],
        generated_smart_files["TOTW #18 - Pg.3"],
        generated_smart_files["TOTW #18 - Pg.4"],
        generated_smart_files["TOTW #18 - Pg.5"],
        generated_smart_files["TOTW #18 - Pg.6"],
        generated_smart_files["TOTW #18 - Pg.7"],
        generated_smart_files["TOTW #18 - Pg.8"],
        generated_smart_files["TOTW #18 - Pg.9"],
        generated_smart_files["TOTW #18 - Pg.10"],
        generated_smart_files["TOTW #18 - Pg.11"],
        generated_smart_files["TOTW #18 - Pg.12"],
        generated_smart_files["TOTW #18 - Pg.13"],
        generated_smart_files["TOTW #18 - Pg.14"],
        generated_smart_files["TOTW #18 - Pg.15"],
        generated_smart_files["TOTW #18 - Pg.16"],
        generated_smart_files["TOTW #18 - Pg.17"],
        generated_smart_files["TOTW #18 - Pg.18"],
        generated_smart_files["TOTW #18 - Pg.19"],
        generated_smart_files["TOTW #18 - Pg.20"],
        generated_smart_files["TOTW #18 - Pg.21"],
        generated_smart_files["TOTW #18 - Pg.22"],
    ]),
    'TOTW #19': new Chapter('TOP OF THE WORLD #19 - WOW YOU\'RE HURT', [
        generated_smart_files["TOTW #19 - Cover"],
        generated_smart_files["TOTW #19 - Pg.1"],
        generated_smart_files["TOTW #19 - Pg.2"],
        generated_smart_files["TOTW #19 - Pg.3"],
        generated_smart_files["TOTW #19 - Pg.4"],
        generated_smart_files["TOTW #19 - Pg.5"],
        generated_smart_files["TOTW #19 - Pg.6"],
        generated_smart_files["TOTW #19 - Pg.7"],
        generated_smart_files["TOTW #19 - Pg.8"],
        generated_smart_files["TOTW #19 - Pg.9"],
        generated_smart_files["TOTW #19 - Pg.10"],
        generated_smart_files["TOTW #19 - Pg.11"],
        generated_smart_files["TOTW #19 - Pg.12"],
    ]),
    'TOTW #20': new Chapter('TOP OF THE WORLD #20 - FIX GUN', [
        generated_smart_files["TOTW #20 - Cover"],
        generated_smart_files["TOTW #20 - Pg.1"],
        generated_smart_files["TOTW #20 - Pg.2"],
        generated_smart_files["TOTW #20 - Pg.3"],
        generated_smart_files["TOTW #20 - Pg.4"],
        generated_smart_files["TOTW #20 - Pg.5"],
        generated_smart_files["TOTW #20 - Pg.6"],
        generated_smart_files["TOTW #20 - Pg.7"],
        generated_smart_files["TOTW #20 - Pg.8"],
        generated_smart_files["TOTW #20 - Pg.9"],
        generated_smart_files["TOTW #20 - Pg.10"],
        generated_smart_files["TOTW #20 - Pg.11"],
        generated_smart_files["TOTW #20 - Pg.12"],
    ]),
    'TOTW #21': new Chapter('TOP OF THE WORLD #21 - BACKGROUND', [
        generated_smart_files["TOTW #21 - Cover"],
        generated_smart_files["TOTW #21 - Pg.1"],
        generated_smart_files["TOTW #21 - Pg.2"],
        generated_smart_files["TOTW #21 - Pg.3"],
        generated_smart_files["TOTW #21 - Pg.4"],
        generated_smart_files["TOTW #21 - Pg.5"],
        generated_smart_files["TOTW #21 - Pg.6"],
        generated_smart_files["TOTW #21 - Pg.7"],
        generated_smart_files["TOTW #21 - Pg.8"],
    ]),
}
let sequential_chapter_pointers = [
    'TOTW #1',
    'TOTW #2',
    'TOTW #3',
    'TOTW #4',
    'TOTW #5',
    'TOTW #6',
    'TOTW #7',
    'TOTW #8',
    'TOTW #9',
    'TOTW #10',
    'TOTW #11',
    'TOTW #12',
    'TOTW #13',
    'TOTW #14',
    'TOTW #15',
    'TOTW #16',
    'TOTW #17',
    'TOTW #18',
    'TOTW #19',
    'TOTW #20',
    'TOTW #21',
]
let remastered_chapter_pointers = [
    'TOTW #1 Remastered',
]

// Exports
export { written_chapters, sequential_chapter_pointers, remastered_chapter_pointers };